# .github/workflows/calling-workflow.yml
name: Calling Workflow

on:
  workflow_dispatch: # Allows this workflow to be manually triggered from the GitHub UI

jobs:
  call_target_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
          repository: anurag3263/REST_ASSUERED_2024
          event-type: trigger-workflow
